# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ff7a55ea4e47426462db03029cb3d9580a8de7979d901edef5488a3711549b00fe89408637f0690134649e7927b08c37ff20b77c21f7f1af21ff184089d3f80

test:
  secret_key_base: f2ce826b1f978eebf552f0c4d575e82f4ab4fe8556ce50c7b9b845b64f3d2eb4796a11fda11c3752a0d73aeddddc9fc6549c9854f6586e0baec43d94441280a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
